<?php
$produtos = array(
    0 => array('id'=>'#122','collection'=>'Bored Ape','price'=>'','image'=>'122-boredApe.png'),
    1 => array('id'=>'#955','collection'=>'Bored Ape','price'=>'','image'=>'955-boredApe.png'),
    2 => array('id'=>'#2087','collection'=>'Bored Ape','price'=>'','image'=>'2087-boredApe.png'),
    3 => array('id'=>'#3368','collection'=>'Bored Ape','price'=>'','image'=>'3368-boredApe.png'),
    4 => array('id'=>'#3650','collection'=>'Bored Ape','price'=>'','image'=>'3650-boredApe.png'),
    5 => array('id'=>'#4303','collection'=>'Bored Ape','price'=>'','image'=>'4303-boredApe.png'),
    6 => array('id'=>'#4671','collection'=>'Bored Ape','price'=>'','image'=>'4671-boredApe.png'),
    7 => array('id'=>'#8470','collection'=>'Bored Ape','price'=>'','image'=>'8470-boredApe.png'),
    8 => array('id'=>'#8520','collection'=>'Bored Ape','price'=>'','image'=>'8520-boredApe.png'),
    9 => array('id'=>'#9996','collection'=>'Bored Ape','price'=>'','image'=>'9996-boredApe.png'),
    10 => array('id'=>'#104','collection'=>'CryptoPunk','price'=>'','image'=>'104-cryptoPunk.png'),
    11 => array('id'=>'#110','collection'=>'CryptoPunk','price'=>'','image'=>'110-cryptoPunk.png'),
    12 => array('id'=>'#7594','collection'=>'CryptoPunk','price'=>'','image'=>'7594-cryptoPunk.png'),
    13 => array('id'=>'#7600','collection'=>'CryptoPunk','price'=>'','image'=>'7600-cryptoPunk.png'),
    14 => array('id'=>'#7604','collection'=>'CryptoPunk','price'=>'','image'=>'7604-cryptoPunk.png'),
    15 => array('id'=>'#7607','collection'=>'CryptoPunk','price'=>'','image'=>'7607-cryptoPunk.png'),
    16 => array('id'=>'#7612','collection'=>'CryptoPunk','price'=>'','image'=>'7612-cryptoPunk.png'),
    17 => array('id'=>'#7613','collection'=>'CryptoPunk','price'=>'','image'=>'7613-cryptoPunk.png'),
    18 => array('id'=>'#7614','collection'=>'CryptoPunk','price'=>'','image'=>'7614-cryptoPunk.png'),
    19 => array('id'=>'#7617','collection'=>'CryptoPunk','price'=>'','image'=>'7617-cryptoPunk.png'),
    20 => array('id'=>'#1023','collection'=>'Azuki','price'=>'','image'=>'1023-azuki.png'),
    21 => array('id'=>'#2599','collection'=>'Azuki','price'=>'','image'=>'2599-azuki.png'),
    22 => array('id'=>'#2905','collection'=>'Azuki','price'=>'','image'=>'2905-azuki.png'),
    23 => array('id'=>'#4385','collection'=>'Azuki','price'=>'','image'=>'4385-azuki.png'),
    24 => array('id'=>'#4614','collection'=>'Azuki','price'=>'','image'=>'4614-azuki.png'),
    25 => array('id'=>'#5083','collection'=>'Azuki','price'=>'','image'=>'5083-azuki.png'),
    26 => array('id'=>'#5214','collection'=>'Azuki','price'=>'','image'=>'5214-azuki.png'),
    27 => array('id'=>'#9024','collection'=>'Azuki','price'=>'','image'=>'9024-azuki.png'),
    28 => array('id'=>'#9201','collection'=>'Azuki','price'=>'','image'=>'9201-azuki.png'),
    29 => array('id'=>'#9445','collection'=>'Azuki','price'=>'','image'=>'9445-azuki.png')
);
?>