<?php
$produtos = array(
    0 => array('code'=>'#122','collection'=>'Bored Ape','price'=>'1 ETH','image'=>'122-boredApe.png'),
    1 => array('code'=>'#955','collection'=>'Bored Ape','price'=>'1 ETH','image'=>'955-boredApe.png'),
    2 => array('code'=>'#2087','collection'=>'Bored Ape','price'=>'1 ETH','image'=>'2087-boredApe.png'),
    3 => array('code'=>'#3368','collection'=>'Bored Ape','price'=>'1 ETH','image'=>'3368-boredApe.png'),
    4 => array('code'=>'#3650','collection'=>'Bored Ape','price'=>'1 ETH','image'=>'3650-boredApe.png'),
    5 => array('code'=>'#4303','collection'=>'Bored Ape','price'=>'1 ETH','image'=>'4303-boredApe.png'),
    6 => array('code'=>'#4671','collection'=>'Bored Ape','price'=>'1 ETH','image'=>'4671-boredApe.png'),
    7 => array('code'=>'#8470','collection'=>'Bored Ape','price'=>'1 ETH','image'=>'8470-boredApe.png'),
    8 => array('code'=>'#8520','collection'=>'Bored Ape','price'=>'1 ETH','image'=>'8520-boredApe.png'),
    9 => array('code'=>'#9996','collection'=>'Bored Ape','price'=>'1 ETH','image'=>'9996-boredApe.png'),
    10 => array('code'=>'#104','collection'=>'CryptoPunk','price'=>'1 ETH','image'=>'104-cryptoPunk.png'),
    11 => array('code'=>'#110','collection'=>'CryptoPunk','price'=>'1 ETH','image'=>'110-cryptoPunk.png'),
    12 => array('code'=>'#7594','collection'=>'CryptoPunk','price'=>'1 ETH','image'=>'7594-cryptoPunk.png'),
    13 => array('code'=>'#7600','collection'=>'CryptoPunk','price'=>'1 ETH','image'=>'7600-cryptoPunk.png'),
    14 => array('code'=>'#7604','collection'=>'CryptoPunk','price'=>'1 ETH','image'=>'7604-cryptoPunk.png'),
    15 => array('code'=>'#7607','collection'=>'CryptoPunk','price'=>'1 ETH','image'=>'7607-cryptoPunk.png'),
    16 => array('code'=>'#7612','collection'=>'CryptoPunk','price'=>'1 ETH','image'=>'7612-cryptoPunk.png'),
    17 => array('code'=>'#7613','collection'=>'CryptoPunk','price'=>'1 ETH','image'=>'7613-cryptoPunk.png'),
    18 => array('code'=>'#7614','collection'=>'CryptoPunk','price'=>'1 ETH','image'=>'7614-cryptoPunk.png'),
    19 => array('code'=>'#7617','collection'=>'CryptoPunk','price'=>'1 ETH','image'=>'7617-cryptoPunk.png'),
    20 => array('code'=>'#1023','collection'=>'Azuki','price'=>'1 ETH','image'=>'1023-azuki.png'),
    21 => array('code'=>'#2599','collection'=>'Azuki','price'=>'','image'=>'2599-azuki.png'),
    22 => array('code'=>'#2905','collection'=>'Azuki','price'=>'','image'=>'2905-azuki.png'),
    23 => array('code'=>'#4385','collection'=>'Azuki','price'=>'','image'=>'4385-azuki.png'),
    24 => array('code'=>'#4614','collection'=>'Azuki','price'=>'','image'=>'4614-azuki.png'),
    25 => array('code'=>'#5083','collection'=>'Azuki','price'=>'','image'=>'5083-azuki.png'),
    26 => array('code'=>'#5214','collection'=>'Azuki','price'=>'','image'=>'5214-azuki.png'),
    27 => array('code'=>'#9024','collection'=>'Azuki','price'=>'','image'=>'9024-azuki.png'),
    28 => array('code'=>'#9201','collection'=>'Azuki','price'=>'','image'=>'9201-azuki.png'),
    29 => array('code'=>'#9445','collection'=>'Azuki','price'=>'','image'=>'9445-azuki.png')
);
?>