<?php
$produtos = array(
    0 => array('id'=>'#122','collection'=>'Bored Ape','price'=>'','image'=>'122-boredApe.png'),
    1 => array('id'=>'#955','collection'=>'Bored Ape','price'=>'','image'=>'955-boredApe.png'),
    2 => array('id'=>'#2087','collection'=>'Bored Ape','price'=>'','image'=>'2087-boredApe.png'),
    3 => array('id'=>'#3368','collection'=>'Bored Ape','price'=>'','image'=>'3368-boredApe.png'),
    4 => array('id'=>'#3650','collection'=>'Bored Ape','price'=>'','image'=>'3650-boredApe.png'),
    5 => array('id'=>'#4303','collection'=>'Bored Ape','price'=>'','image'=>'4303-boredApe.png'),
    6 => array('id'=>'#4671','collection'=>'Bored Ape','price'=>'','image'=>'4671-boredApe.png'),
    7 => array('id'=>'#8470','collection'=>'Bored Ape','price'=>'','image'=>'8470-boredApe.png'),
    8 => array('id'=>'#8520','collection'=>'Bored Ape','price'=>'','image'=>'8520-boredApe.png'),
    9 => array('id'=>'#9996','collection'=>'Bored Ape','price'=>'','image'=>'9996-boredApe.png'),
    10 => array('id'=>'#104','collection'=>'CryptoPunk','price'=>'','image'=>'104-cryptoPunk.png'),
    11 => array('id'=>'#110','collection'=>'CryptoPunk','price'=>'','image'=>'110-cryptoPunk.png'),
    12 => array('id'=>'#7594','collection'=>'CryptoPunk','price'=>'','image'=>'7594-cryptoPunk.png'),
    13 => array('id'=>'#7600','collection'=>'CryptoPunk','price'=>'','image'=>'7600-cryptoPunk.png'),
    14 => array('id'=>'#7604','collection'=>'CryptoPunk','price'=>'','image'=>'7604-cryptoPunk.png'),
    15 => array('id'=>'#7607','collection'=>'CryptoPunk','price'=>'','image'=>'7607-cryptoPunk.png'),
    16 => array('id'=>'#7612','collection'=>'CryptoPunk','price'=>'','image'=>'7612-cryptoPunk.png'),
    17 => array('id'=>'#7613','collection'=>'CryptoPunk','price'=>'','image'=>'7613-cryptoPunk.png'),
    18 => array('id'=>'#7614','collection'=>'CryptoPunk','price'=>'','image'=>'7614-cryptoPunk.png'),
    19 => array('id'=>'#7617','collection'=>'CryptoPunk','price'=>'','image'=>'7617-cryptoPunk.png'),
    20 => array('id'=>'','collection'=>'','price'=>'','image'=>''),
    21 => array('id'=>'','collection'=>'','price'=>'','image'=>''),
    22 => array('id'=>'','collection'=>'','price'=>'','image'=>''),
    23 => array('id'=>'','collection'=>'','price'=>'','image'=>''),
    24 => array('id'=>'','collection'=>'','price'=>'','image'=>''),
    25 => array('id'=>'','collection'=>'','price'=>'','image'=>''),
    26 => array('id'=>'','collection'=>'','price'=>'','image'=>''),
    27 => array('id'=>'','collection'=>'','price'=>'','image'=>''),
    28 => array('id'=>'','collection'=>'','price'=>'','image'=>''),
    29 => array('id'=>'','collection'=>'','price'=>'','image'=>'')
);
?>